/*
 *
 * EmployeeFinanceContainer constants
 *
 */

export const GET_CURRENT_CONTRACTS = 'GET_CURRENT_CONTRACTS';
export const GET_ENDED_CONTRACTS = 'GET_ENDED_CONTRACTS';
export const CHANGE_STATE_CURRENT_CONTRACTS = 'CHANGE_STATE_CURRENT_CONTRACTS';
export const CHANGE_STATE_ENDED_CONTRACTS = 'CHANGE_STATE_ENDED_CONTRACTS';
export const SET_HEADER = 'SET_HEADER';
export const CHANGE_HEADER_STATE = 'CHANGE_HEADER_STATE';
export const CHANGE_STATE_AWAITED_CONTRACTS = 'CHANGE_STATE_AWAITED_CONTRACTS';
export const GET_AWAITED_CONTRACTS = 'GET_AWAITED_CONTRACTS';

export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
