/*
 *
 * RegistrationEmployee constants
 *
 */
// actions
export const GET_SKILLS_FILTER = 'GET_SKILLS_FILTER';
export const CHOOSE_SKILL_FILTER = 'CHOOSE_SKILL_FILTER';
export const DELETE_SKILL_FILTER_FROM_POSSIBLE = 'DELETE_SKILL_FILTER_FROM_POSSIBLE';
export const ADD_SKILL_FILTER_TO_POSSIBLE = 'ADD_SKILL_FILTER_TO_POSSIBLE';
export const DELETE_SKILL_FILTER_FROM_CHOOSEN = 'DELETE_SKILL_FILTER_FROM_CHOOSEN';
export const DELETE_SKILL_FROM_SKILLS_FILTER = 'DELETE_SKILL_FROM_SKILLS_FILTER';
export const CLEAR_SKILLS_FILTER_SELECTOR = 'CLEAR_SKILLS_FILTER_SELECTOR';
export const SET_SKILLS_FILTERS = 'SET_LANGUAGES';

// state
export const CHOOSEN = 'CHOOSEN';
export const NOT_CHOOSEN = 'NOT_CHOOSEN';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const NONE = 'NONE';
