/*
 *
 * RegistrationEmployee constants
 *
 */
// actions
export const GET_EMPLOYEE_REGISTRATION_STEP = 'GET_EMPLOYEE_REGISTRATION_STEP';
export const CHOOSE_AVATAR = 'CHOOSE_AVATAR';
// buttons
export const CHANGE_SUBMIT_SPECIFICATION_BUTTON_STATUS = 'CHANGE_SUBMIT_SPECIFICATION_BUTTON_STATUS';
export const CHANGE_SUBMIT_ABOUT_BUTTON_STATUS = 'CHANGE_SUBMIT_ABOUT_BUTTON_STATUS';

// state
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const NONE = 'NONE';
