/*
 *
 * MainInformation constants
 *
 */

export const CHANGE_STATE_COMPANY_PROFILE_MAIN_INFO = 'CHANGE_STATE_COMPANY_PROFILE_MAIN_INFO';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const GET_COMPANY_PROFILE_MAIN_INFO = 'GET_COMPANY_PROFILE_MAIN_INFO';
