/*
 *
 * MainInformation constants
 *
 */

export const CHANGE_STATE_PROFILE_MAIN_INFO = 'CHANGE_STATE_PROFILE_MAIN_INFO';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const GET_PROFILE_MAIN_INFO = 'GET_PROFILE_MAIN_INFO';
export const RESET_MAIN_INFO_EMPLOYEE_PROFILE = 'RESET_MAIN_INFO_EMPLOYEE_PROFILE';
