/*
 *
 * Skills constants
 *
 */

export const CHANGE_STATE_SPECIFICATIONS_SKILLS_EMPLOYEE = 'CHANGE_STATE_SPECIFICATIONS_SKILLS_EMPLOYEE';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const GET_SPECIFICATIONS_SKILLS_EMPLOYEE = 'GET_SPECIFICATIONS_SKILLS_EMPLOYEE';
export const RESET_SKILLS_EMPLOYEE_PROFILE = 'RESET_SKILLS_EMPLOYEE_PROFILE';
