/*
 *
 * InputQuestionCreation constants
 *
 */

export const CHANGE_SUBMIT_CREATION_INPUT_QUESTION_BUTTON_STATUS = 'CHANGE_SUBMIT_CREATION_INPUT_QUESTION_BUTTON_STATUS';
export const CLEAR_INPUT_QUESTION_CREATION = 'CLEAR_INPUT_QUESTION_CREATION';
