/*
 *
 * ContinueRegistration constants
 *
 */

export const UP_REGISTRATION_STEP = 'UP_REGISTRATION_STEP';
export const DOWN_REGISTRATION_STEP = 'DOWN_REGISTRATION_STEP';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_SUBMIT_BUTTON_STATE = 'CHANGE_SUBMIT_BUTTON_STATE';
export const CHANGE_SUBMIT_EMAIL_BUTTON_STATE = 'CHANGE_SUBMIT_EMAIL_BUTTON_STATE';
export const CHANGE_SUBMIT_EMAIL_VERIFICATION_BUTTON_STATE = 'CHANGE_SUBMIT_EMAIL_VERIFICATION_BUTTON_STATE';
export const CLEAR = 'CLEAR';

export const LOADED = 'LOADED';
export const EMPLOYEE = 'EMPLOYEE';
export const COMPANY = 'COMPANY';
