/*
 *
 * TestNavigation constants
 *
 */

export const DEFAULT_ACTION = 'DEFAULT_ACTION';
export const CHANGE_STATE_TEST_QESTIONS = 'CHANGE_STATE_TEST_QESTIONS';
export const CHANGE_CURRENT_QUESTION = 'CHANGE_CURRENT_QUESTION';
export const CLEAR_NAVIGATION_TEST_REDUCER = 'CLEAR_NAVIGATION_TEST_REDUCER';
export const GET_TEST_QUESTIONS = 'GET_TEST_QUESTIONS';
export const MARK_QWESTION_AS_VIEWED = 'MARK_QWESTION_AS_VIEWED';

export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const NOT_LOADED = 'NOT_LOADED';
