/*
 *
 * RegistrationEmployee constants
 *
 */
// actions
export const DEFAULT_ACTION = 'app/RegistrationEmployee/DEFAULT_ACTION';
export const GET_EMPLOYEE_REGISTRATION_STEP = 'GET_EMPLOYEE_REGISTRATION_STEP';
export const GET_EMPLOYEE_SPECIFICATION_LIST = 'GET_EMPLOYEE_SPECIFICATION_LIST';
export const GET_EMPLOYEE_SKILLS_LIST = 'GET_EMPLOYEE_SKILLS_LIST';
export const CHOOSE_EMPLOYEE_SPECIFICATION_LIST = 'CHOOSE_EMPLOYEE_SPECIFICATION_LIST';
export const ADD_SKILL_TO_SPECIFICATION = 'ADD_SKILL_TO_SPECIFICATION';

// state
export const CHOOSEN = 'CHOOSEN';
export const NOT_CHOOSEN = 'NOT_CHOOSEN';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const NONE = 'NONE';
