export const CHANGE_STATE_NOTIFICATIONS = 'CHANGE_STATE_NOTIFICATIONS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const NOT_LOADED = 'NOT_LOADED';
