/*
 *
 * MultipleChoiceQuestionCreation constants
 *
 */

export const CHANGE_SUBMIT_CREATION_MULTIPLE_QUESTION_BUTTON_STATUS = 'CHANGE_SUBMIT_CREATION_MULTIPLE_QUESTION_BUTTON_STATUS';
export const CLEAR_MULTIPLE_QUESTION_CREATION = 'CLEAR_MULTIPLE_QUESTION_CREATION';
