/*
 *
 * TestCreation constants
 *
 */

export const CHANGE_SUBMIT_CREATION_TEST_BUTTON_STATUS = 'CHANGE_SUBMIT_CREATION_TEST_BUTTON_STATUS';
export const CLEAR_TEST_CREATION = 'CLEAR_TEST_CREATION';
