/*
 *
 * Skills constants
 *
 */

export const CHANGE_STATE_SPECIFICATIONS_SKILLS_VACANCY = 'CHANGE_STATE_SPECIFICATIONS_SKILLS_VACANCY';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const GET_SPECIFICATIONS_SKILLS_VACANCY = 'GET_SPECIFICATIONS_SKILLS_VACANCY';
export const RESET_SKILLS_VACANCY = 'RESET_SKILLS_VACANCY';
