/*
 *
 * RegistrationEmployee constants
 *
 */
// actions
export const GET_EMPLOYEE_SPECIFICATION_LIST = 'GET_EMPLOYEE_SPECIFICATION_LIST';
export const GET_EMPLOYEE_SKILLS_LIST = 'GET_EMPLOYEE_SKILLS_LIST';
export const CHOOSE_EMPLOYEE_SPECIFICATION_LIST = 'CHOOSE_EMPLOYEE_SPECIFICATION_LIST';
export const ADD_SKILL_TO_SPECIFICATION = 'ADD_SKILL_TO_SPECIFICATION';
export const DELETE_SPECIFICATION_FROM_POSSIBLE = 'DELETE_SPECIFICATION_FROM_POSSIBLE';
export const ADD_SPECIFICATION_TO_POSSIBLE = 'ADD_SPECIFICATION_TO_POSSIBLE';
export const DELETE_SKILL_FROM_POSSIBLE = 'DELETE_SKILL_FROM_POSSIBLE';
export const ADD_SKILL_TO_POSSIBLE = 'ADD_SKILL_TO_POSSIBLE';
export const DELETE_SPECIFICATION_FROM_CHOOSEN = 'DELETE_SPECIFICATION_FROM_CHOOSEN';
export const DELETE_SKILL_FROM_SPECIFICATION = 'DELETE_SKILL_FROM_SPECIFICATION';
export const CLEAR = 'CLEAR';

// state
export const CHOOSEN = 'CHOOSEN';
export const NOT_CHOOSEN = 'NOT_CHOOSEN';
export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
export const NONE = 'NONE';
