/*
 *
 * CompanyFinanceContainer constants
 *
 */


export const GET_OPEN_VACANCIES = 'GET_OPEN_VACANCIES';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const SET_HEADER = 'SET_HEADER';
export const CHANGE_BALANCE = 'CHANGE_BALANCE';
export const CHANGE_HEADER_STATE = 'CHANGE_HEADER_STATE';
export const CHANGE_STATE_OPEN_VACANCIES = 'CHANGE_STATE_OPEN_VACANCIES';
export const CHANGE_STATE_EMPLOYEES = 'CHANGE_STATE_EMPLOYEES';
export const CHANGE_STATE_PAYMENTS = 'CHANGE_STATE_PAYMENTS';

export const LOADING = 'LOADING';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
