/*
 *
 * CompanyFinanceContainer constants
 *
 */


export const GET_INTERLOCATORS = 'GET_INTERLOCATORS';
export const CHANGE_CURRENT_INTERLOCATOR = 'CHANGE_CURRENT_INTERLOCATOR';
export const CHANGE_STATE_INTERLOCATORS = 'CHANGE_STATE_INTERLOCATORS';
export const CHANGE_CURRENT_INTERLOCATOR_STATUS = 'CHANGE_CURRENT_INTERLOCATOR_STATUS';

export const LOADING = 'LOADING';
export const NOT_CHOOSEN = 'NOT_CHOOSEN';
export const CHOOSEN = 'CHOOSEN';
export const NOT_LOADED = 'NOT_LOADED';
export const LOADED = 'LOADED';
